<?php

return [

    '^/?$' => ['cMain', 'index'],
    '^/registration/?$' => ['cRegistration', 'index'],
    '^/registration/repeat/?$' => ['cRegistration', 'repeat'],
    '^/registration/confirm/?$' => ['cRegistration', 'confirm'],
    '^/authorization/?$' => ['cAuthorization', 'index'],
    '^/authorization/exit/?$' => ['cAuthorization', 'deauth'],
    '^/authorization/repair/?$' => ['cAuthorization', 'repair'],
    '^/authorization/repair/(.+)$' => ['cAuthorization', 'confirmHash', '$1'],
    '^/download/([0-9]+)/?$' => ['cDownload', 'download', '$1'],
    '^/projects/?$' => ['cProject', 'index'],
    '^/admin/?$' => ['cProject', 'admin'],
    '^/projects/new/?$' => ['cProject', 'create'],
    '^/projects/delete/([0-9]+)/?$' => ['cProject', 'delete', '$1'],
    '^/projects/([0-9]+)/appoint_coach/?$' => ['cProject', 'appoint', '$1 visiting_coach'],
    '^/projects/([0-9]+)/([0-9]+)/?$' => ['cProject', 'stage', '$1 $2'],
    '^/projects/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/?$' => ['cProject', 'card', '$1 $2 $3 $4'],
    '^/projects/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/reactivate/?$' => ['cProject', 'reactivate', '$1 $2 $3 $4'],
    '^/projects/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/finish/?$' => ['cProject', 'finish', '$1 $2 $3 $4'],
    '^/projects/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/appoint_manager/?$' => ['cProject', 'appoint', '$1 $2 $3 $4 project_manager'],
    '^/projects/([0-9]+)/([0-9]+)/([0-9]+)/([0-9]+)/appoint_coach/?$' => ['cProject', 'appoint', '$1 $2 $3 $4 visiting_coach'],
    '^/user/([0-9]+)/?$' => ['cUser', 'profile', '$1'],
    '^/avatar/([0-9]+)/?$' => ['cUser', 'avatar', '$1'],
    '^/images/([0-9a-zA-Z]+\.[a-z0-9]+)/?$' => ['cFile', 'image', '$1'],
    '^/styles/([0-9a-zA-Z]+\.[a-z0-9]+)/?$' => ['cFile', 'style', '$1'],
    '^/ajax/save/([0-9]+)/?$' => ['Ajax', 'save', '$1'],
    '^/ajax/user/([0-9]+)/?$' => ['Ajax', 'saveUser', '$1'],
    '^/ajax/form/([0-9]+)/?$' => ['Ajax', 'saveFormUpd', '$1'],
    '^/ajax/checkmsg/([0-9]+)/?$' => ['Ajax', 'checkMsg', '$1'],
    '^/formtest/?$' =>['cProject', 'form'],
    '.*' => ['c404', 'index'],
];
